# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5b71e2e8ab2edaeae6481c54e75ac419ae1fb73b3d8efb24c5c47d37e73010a8db3ef54e5bccd65105551113cc5bd4dabc6145577168ffbf09ce88d7d4e7325

test:
  secret_key_base: 809b51fe8effb22962f29e905ee4ee2a79b32c6c42bd1fdc3b7add529a03d38845317c4c9f3c0eb3361d64cb5c15d71ae25f5959dbb294807f7b32cbb2347f59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
